dist: trusty
services:
  - docker
language: node_js
node_js:
  - "12.3.0"
before_install:
    - cd $TRAVIS_BUILD_DIR/docker-101
install:
    - npm ci
before_script:
    - cd $TRAVIS_BUILD_DIR/docker-101
script:
    - npm run lint
    - npm run flow
